name: bpub-alpha
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  issues: write
concurrency:
  group: bpub
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: install stuff
        run: |
          brew install pandoc
      - name: assume role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: get caller identity
        run: aws sts get-caller-identity
      - name: prepare temp dir
        run: mkdir -p temp/assets
      - name: create pages
        run: .github/workflows/pages.sh create
      - name: sync
        run: |
          cd temp
          ls -A
          aws s3 sync . s3://jj-blog-test/pages/ --delete
          aws s3 mv s3://jj-blog-test/pages/ s3://jj-blog-test/pages/ --exclude * --include '*.html' \
            --no-guess-mime-type --content-type="text/html" --metadata-directive="REPLACE"
