name: bpub-alpha
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  issues: write
concurrency:
  group: bpub
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: install stuff
        run: |
          sudo apt-get update
          sudo apt-get install python3.9
          pip3 install -r .github/workflows/req.txt
      - name: assume role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: get caller identity
        run: aws sts get-caller-identity
      - name: prepare upload dir
        run: mkdir -p upload/assets
      - name: create pages
        run: python3.9 .github/workflows/render.py
      - name: sync index
        run: |
          cd index
          aws s3 sync . s3://jj-blog-test/ --delete
      - name: sync pages
        run: |
          cd upload
          ls -R
          aws s3 sync . s3://jj-blog-test/pages/ --delete --exclude "*.*" --content-type="text/html" \
            --no-guess-mime-type --metadata-directive "REPLACE"
          aws s3 sync . s3://jj-blog-test/pages/ --delete --exclude "*" --include "*.*"
      # TODO: invalidate cloudfront cache?
#      - name: invalidate cloudfront cache
#        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
